services:
  - name: "Portainer"
    logo: "assets/portainer.png"
    url: "http://${HOST_IP}:9000"
    type: "docker"
    tag: "management"
  - name: "Nginx Proxy Manager"
    logo: "assets/nginx.png"
    url: "http://${HOST_IP}:81"
    type: "app"
    tag: "network"
  - name: "N8N"
    logo: "assets/n8n.png"
    url: "http://${HOST_IP}:5678"
    type: "app"
    tag: "workflow"
  - name: "Qdrant"
    logo: "assets/qdrant.png"
    url: "http://${HOST_IP}:6333"
    type: "app"
    tag: "database"
  - name: "Open Web UI"
    logo: "assets/openwebui.png"
    url: "http://${HOST_IP}:3000"
    type: "app"
    tag: "interface"
  - name: "Ollama"
    logo: "assets/ollama.png"
    url: "http://${HOST_IP}:11434"
    type: "app"
    tag: "AI"
