services:
  - name: "Portainer"
    logo: "assets/portainer.png"
    url: "http://localhost:9000"
    type: "docker"
    tag: "management"
  - name: "Nginx Proxy Manager"
    logo: "assets/nginx.png"
    url: "http://localhost:81"
    type: "app"
    tag: "network"
  - name: "N8N"
    logo: "assets/n8n.png"
    url: "http://localhost:5678"
    type: "app"
    tag: "workflow"
  - name: "Qdrant"
    logo: "assets/qdrant.png"
    url: "http://localhost:6333"
    type: "app"
    tag: "database"
  - name: "Open Web UI"
    logo: "assets/openwebui.png"
    url: "http://localhost:3000"
    type: "app"
    tag: "interface"
  - name: "Ollama"
    logo: "assets/ollama.png"
    url: "http://localhost:11434"
    type: "app"
    tag: "AI"
