---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- AI Services:
    - Open Web UI:
        href: "http://10.10.37.118:3000"
        description: "User Interface"
        icon: "ollama.png"
    - Ollama:
        href: "http://10.10.37.118:11434"
        description: "AI Service"
        icon: "ollama.png"
    - Bolt:
        href: "http://10.10.37.118:5173"
        description: "Code Editor"
        icon: "https://developer.stackblitz.com/img/logo/stackblitz-bolt-blue.svg"
- Managment Services:
    - Portainer:
        href: "http://10.10.37.118:9000"
        description: "Management Interface"
        icon: "portainer.png"
- Automation Services:
    - N8N:
        href: "http://10.10.37.118:5678"
        description: "Workflow Automation"
        icon: "n8n.png"
- Database Services:
    - Qdrant:    
        href: "http://10.10.37.118:6333/dashboard"
        description: "Database Service"
        icon: "https://avatars.githubusercontent.com/u/73504361?s=200&v=4"
    - Google Drive:
        href: "https://drive.google.com/drive/my-drive"
        description: "Cloud Storage"
        icon: "https://upload.wikimedia.org/wikipedia/commons/1/12/Google_Drive_icon_%282020%29.svg"
